name: account
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sembast: ^3.8.2
  path_provider: ^2.1.5
  path: ^1.9.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.5.0  # ✅ เพิ่มไลบรารีไอคอนวิทยาศาสตร์ (microscope, atom, rocket)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/flutter_logo.png  # ระบุไฟล์เฉพาะ
    - assets/images/  # โหลดทั้งโฟลเดอร์ (ถ้ามีหลายไฟล์)
  fonts:
    - family: ScienceFont
      fonts:
        - asset: assets/fonts/ScienceFont-Regular.ttf
        - asset: assets/fonts/ScienceFont-Bold.ttf
          weight: 700
